import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SpotifyPlayer from "react-spotify-web-playback";
import { useEffect } from "react";
import { useSession } from "next-auth/react";
import Link from "next/link";

export default function About() {
  const session = useSession();
  console.log(session);
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World</h1>
      <p>about me</p>
    </div>
  );
}
